dist: bionic
os: linux
language: python
python:
  - "3.8"

branches:
 only:
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get -y install nmap

install:
  - pip install -r requirements.txt

script: pytest
